### ISSUE TITLE
Configurer le Dependabot

### ISSUE THREAD

**Issue by HeyHeyChicken** [HeyHeyChicken/EBP-EVA-Battle-Plan-Tools#2]
Pour configurer Dependabot pour un projet Node.js, ajoute un fichier .github/dependabot.yml à la racine du dépôt avec le contenu suivant :

yaml

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"          # Répertoire du fichier package.json
    schedule:
      interval: "weekly"    # daily | weekly | monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
```

Étapes :
- Crée le dossier .github à la racine si absent.
- Crée le fichier dependabot.yml dans .github.
- Copie-colle le contenu ci-dessus.
- Push sur GitHub.

Dependabot commencera à scanner les dépendances listées dans package.json et package-lock.json.
